project:
  type: book

book:
  title: "Quantitative Finance Lab"
  author: "Ramtin Asadi"
  chapters:
    - index.qmd
    - overview.qmd
    - ../notebooks/01_yield_curve_construction.ipynb

format:
  html:
    theme: cosmo

output-dir: ../docs
